LiberTEM/LiberTEM-live

- examples/merlin-digital-micrograph.py
- packaging/zenodo-upload.json
* Include 3D Magic
* No GSoC for LiberTEM-live, I guess
* Update GMS following the current Merlin UDF example
* [N/A] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [N/A] I have added/updated test cases
> Update Zenodo template; update GMS example

- prototypes/test_get_tiles.ipynb
- src/libertem_live/detectors/k2is/proto.py
- tests/detectors/test_k2is.py
> Packet reorder cont.

- prototypes/test_get_tiles.ipynb
- src/libertem_live/detectors/k2is/proto.py
- tests/detectors/test_k2is.py
> Effective warmup

- README.rst
- docs/source/reference.rst
- docs/source/usage.rst
- examples/run-udf-on-merlin-data.ipynb
- src/libertem_live/api.py
- src/libertem_live/detectors/merlin/control.py
- src/libertem_live/detectors/merlin/sim.py
Finishing touches from docs review
Thx @sk1p!
* [N/A] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [N/A] I have added/updated test cases
> Documentation tuning

- README.rst
- docs/source/changelog.rst
- docs/source/references-libertem_live.bib
Closes #1 
* [N/A] I have added/updated test cases
* [N/A] `/azp run libertem.libertem-live-data` passed
> Zenodo and pre-commit badges, updated reference

- tests/detectors/test_merlin.py
> Test MemFD only on Linux

- azure-pipelines.yml
Taken from #36 - sync with LiberTEM/LiberTEM which should fix the Mac OS issue, among others
> Updates for CI

- src/libertem_live/detectors/merlin/acquisition.py
- tests/detectors/merlin/test_merlin.py
> Fix tiling scheme so that `process_partition()` works

- azure-pipelines-data.yml
- docs/source/conf.py
- docs_requirements.txt
- setup.cfg
- tox.ini
Port of https://github.com/LiberTEM/LiberTEM/pull/1283
> Fixes for multiprocessing coverage; misc. CI fixes

- src/libertem_live/detectors/dectris/DEigerClient.py
> Replace license header with the correct (MIT) license

- setup.py
- src/libertem_live/detectors/dectris/acquisition.py
- tests/detectors/dectris/test_dectris.py
Needs https://github.com/LiberTEM/LiberTEM-dectris-rs/pull/10
> Remove dependency on bitshuffle package

- ci/run-with-sim.sh
- src/libertem_live/api.py
- src/libertem_live/detectors/dectris/sim.py
> Error message fixup; try harder to kill sims on exit

- azure-pipelines-data.yml
> Try to fix docs deployment

- azure-pipelines-data.yml
- codecov.yml
- scripts/codecov.sh
Also some fixups for #61 to not crash `docs_deploy` in pull requests
> coverage: use new uploader

- .github/workflows/trigger-pages-rebuild.yml
> Trigger libertem.github.io rebuild on push to master

- .github/workflows/trigger-pages-rebuild.yml
> Pages trigger: fix JSON

- azure-pipelines-data.yml
> Cleanup before building and uploading sdist/wheels

- azure-pipelines-data.yml
- src/libertem_live/detectors/dectris/sim.py
Adjust trigger for stable branches; fix dectris sim logger
> Small improvements

- tests/detectors/dectris/test_dectris.py
> Remove version check, as we depend on LiberTEM v0.11+ anyways

- setup.py
> Need flask if you want to use the dectris sim

- override_requirements.txt
Install released LiberTEM version in tests
> Disable override for LiberTEM/LiberTEM

- MANIFEST.in
- src/libertem_live/detectors/merlin/sim.py
Adds license file for detectors to Manifest (feel free to delete the PR and commit direct to master!)
> Add detectors/LICENSE

- src/libertem_live/detectors/merlin/decoders.py
- src/libertem_live/detectors/merlin/utils.py
> Fix numba-related deprecation warnings

- scripts/release
- scripts/requirements.txt
Extracts some variables for easier merging and adds initial github actions support.
Also performs additional sanity check when bumping the version (newer version must be larger)
> Sync release script with LiberTEM{,-blobfinder}

- scripts/release
> Initialize with the correct environment

- conftest.py
Otherwise, parallel test runs will interfere with another
> Don't pin test workers

- scripts/codecov.sh
Port of https://github.com/LiberTEM/LiberTEM/pull/1471
> Update codecov uploader binary version

- docs_requirements.txt
> Restrict sphinx version to fix documentation build

- .github/workflows/ci.yml
Sibling of https://github.com/LiberTEM/LiberTEM/pull/1579
> Test on M1 macs (`macos-14`)

- .github/dependabot.yml
- .github/workflows/ci.yml
> Add weekly dependabot for github actions

- azure-pipelines-data.yml
Otherwise, builds for `master` won't properly submit their coverage.
Sibling of https://github.com/LiberTEM/LiberTEM/pull/1594
> Codecov needs the token in azure, too
