LiberTEM/LiberTEM-live

prototypes/test_get_tiles.ipynb
src/libertem_live/detectors/k2is/decode.py
src/libertem_live/detectors/k2is/proto.py
tests/detectors/test_k2is.py

The happy case is tested and works
TODO: Test all the things that can happen when data gets scrambled
TODO: performance -- not using numba to the fullest extent

Implement the "three buffer reordering" for real packets

---

.pre-commit-config.yaml
docs/source/conf.py
scripts/release
src/libertem_live/detectors/merlin/sim.py
tests/conftest.py
tests/detectors/test_merlin.py
tests/test_smoke.py

select.poll() doesn't always seem to be available on Windows
* [N/A] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [N/A] I have added/updated documentation for all user-facing changes
* [N/A] I have added/updated test cases

Use select.select() instead of select.poll()

---

docs/source/changelog/bugfix/iter.rst
src/libertem_live/api.py
src/libertem_live/detectors/common.py
src/libertem_live/detectors/merlin/data.py
tests/detectors/test_merlin.py

Edit: Now closes #29 thanks to fix by @sk1p!
This PR is just a failing test case since I couldn't get it to work properly. It is based on #29 
The reason that it fails is that we have to keep the connection until the computation is complete, i.e. until the result is awaited or the async generator consumed. The sync case is fixed in #29.
@sk1p could you have a look? I am not sure how live processing in an async context
should be implemented, since we have to read the data in the proper
sequence from one socket.
Use case for this API would probably be integration in an async GUI application? Or should we not support async at all and throw a `NotImplementedError` if `sync` is `False`?

Async with real detector

---

azure-pipelines-data.yml
docs_requirements.txt
setup.py
src/libertem_live/detectors/merlin/acquisition.py
src/libertem_live/detectors/merlin/data.py
src/libertem_live/detectors/merlin/sim.py
tests/detectors/merlin/test_merlin.py

Because we are currently still using LiberTEM internal APIs in LiberTEM-live, we need to keep them in sync.
This bumps the LiberTEM dependency to v0.9, too - we could work around this with some effort, but it would make the code a bit less readable (i.e. duplication of tileshape  negotiation related code in dataset and partition classes)
- [N/A] Make sure this is all the code changes needed - might need additional tests!

LiberTEM v0.9 compatibility

---

src/libertem_live/detectors/dectris/acquisition.py
tests/detectors/dectris/test_dectris.py

* Already set base shape to full frames instead of forcing it after with adjust_tileshape(), meaning it doesn't hit the issue fixed in https://github.com/LiberTEM/LiberTEM/pull/1355
* Include correction in test case that would trigger the issue
* [N/A] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [N/A] I have added/updated documentation for all user-facing changes

Fix issues with tile shape adjustment for corrections

---

src/libertem_live/detectors/merlin/sim.py

From issue #72 adding a `--manual-trigger` option to the Merlin simulator. Needs a similar update for the Dectris simulator.

Manual trigger for Merlin sim

---

src/libertem_live/detectors/dectris/acquisition.py
src/libertem_live/detectors/dectris/connection.py
tests/detectors/dectris/test_dectris.py

* Proper support for `wait_for_acquisition(timeout=None)`
* Don't crash when trying to use active mode after having used passive mode before on the same connection

Dectris UX improvements

---

MANIFEST.in
packaging/creators.json
setup.cfg

Include tests in source tarball to allow testing during conda-build

Include tests in source tarball

---

docs/source/changelog/misc/mock_merlin_ds.rst
packaging/creators.json
tests/detectors/merlin/conftest.py
tests/detectors/merlin/test_merlin_mockds.py

Adds generation of a small fake MIB dataset which can run in the simulator and be tested.
Adds a test for passive mode, active mode, and trigger + garbage active mode.
In the future could add tests for raw mode rather than just integer mode, and also add this dataset generation to LiberTEM.

Add mock Merlin MIB DataSet and simulator tests

---

conftest.py
test_requirements.txt

In CI, there are possibly parallel test runs that oversubscribe the CPU. Limit to a max of 4 workers to prevent this.

Limit number of workers for testing

---

src/libertem_live/detectors/asi_tpx3/sim.py
tests/detectors/asi_tpx3/test_asi_tpx3_sim.py

Fix for nav_shape != (32, 32) in asi tpx3 sim

---

.github/workflows/ci.yml
setup.py

This reverts commit 2935166fac26e5961b54e02b477a26ddc90baa96.
Also require current `sparseconverter` version.

Revert "Pin Python 3.7 version in CI for macos-latest"

---

azure-pipelines-data.yml
conftest.py
docs/source/changelog/features/udf-cancellation.rst
docs/source/examples.rst
src/libertem_live/detectors/asi_tpx3/acquisition.py
src/libertem_live/detectors/dectris/acquisition.py
src/libertem_live/detectors/merlin/acquisition.py
tests/detectors/dectris/test_mocked.py
tests/detectors/merlin/test_merlin_mockds.py

Properly raise `JobCancelledError` if the data stream is interrupted.

UDF Cancellation

---

.github/workflows/ci.yml
docs_requirements.txt

Re-enable `tox-uv`

---

src/libertem_live/api.py
src/libertem_live/detectors/asi_tpx3/acquisition.py
src/libertem_live/detectors/base/acquisition.py
src/libertem_live/detectors/dectris/acquisition.py
src/libertem_live/detectors/memory/acquisition.py
src/libertem_live/detectors/merlin/acquisition.py
src/libertem_live/detectors/merlin/connection.py
tests/test_api.py

~~Mostly right now useful for the test case - I'm not really happy about the implementation.~~

`update_parameters_experimental` w/ sync `run_udf_iter`

---

.github/workflows/ci.yml
docs_requirements.txt
tests/detectors/merlin/conftest.py

The corresponding tests should already be marked anyways.

Fixtures can't be `mark`ed

---

azure-pipelines-data.yml
src/libertem_live/detectors/merlin/decoders.py
tox.ini

Try to be consistent with other jobs.

Fix `docs-check` job; numpy 2.x fixes

---

azure-pipelines-data.yml
conftest.py
docs/source/changelog/bugfix/mib-simulator-fixes.rst
docs/source/detectors/merlin.rst
src/libertem_live/detectors/common.py
src/libertem_live/detectors/merlin/sim.py
tests/detectors/merlin/test_merlin.py

* Allow multiple acquisitions per connection in triggered mode
* Fix acquisition header and sequence numbers in continuous mode and enforce disabled cache in this case
* More correct control socket handling - read and use the MPX prefix

Update MIB simulator

---

src/libertem_live/udf/monitor.py

See also https://github.com/LiberTEM/LiberTEM/pull/1684
Probably one will have to do a two-step rollout, first making the constants available and then incluing them in BACKEND_ALL?

Support for SciPy sparse arrays

---

docs/source/usage.rst

* Clarify `LiveContext` lifetime
* Add section on `run_udf_iter`

Documentation updates

---

src/libertem_live/detectors/merlin/sim.py

In real usage, the number of frames per partition is a lot smaller...

No need to warmup with such a large `stop_before_frame` value

---

pytest.ini
tests/detectors/dectris/test_dectris.py

Like https://github.com/LiberTEM/LiberTEM/pull/1699 - fix remaining `DeprecationWarning`.

Fix deprecation warning on sparse.COO coords
